/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_ywl5320_bsdiff_BsDiffYwl5320Util */

#ifndef _Included_com_ywl5320_bsdiff_BsDiffYwl5320Util
#define _Included_com_ywl5320_bsdiff_BsDiffYwl5320Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ywl5320_bsdiff_BsDiffYwl5320Util
 * Method:    bsDiffFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ywl5320_bsdiff_BsDiffYwl5320Util_bsDiffFile
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
