/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ywl5320_bspatchywl5320_BsPatchYwl5320Util */

#ifndef _Included_com_ywl5320_bspatchywl5320_BsPatchYwl5320Util
#define _Included_com_ywl5320_bspatchywl5320_BsPatchYwl5320Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ywl5320_bspatchywl5320_BsPatchYwl5320Util
 * Method:    bsPatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ywl5320_bspatchywl5320_BsPatchYwl5320Util_bsPatch
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
